language: ruby
notifications:
  email:
    - ivanzotov@gmail.com
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_script:
  - "rake app:railties:install:migrations"
  - "rake app:db:create"
  - "rake app:db:migrate"
script: CODECLIMATE_REPO_TOKEN=38e7fdce39a5db2d6cb08e5a7244b4aac1655407a82ac1d38e20cda242156364 DB=$DB bundle exec rake spec
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - rbx-2.2.5
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

addons:
  code_climate:
    repo_token: 38e7fdce39a5db2d6cb08e5a7244b4aac1655407a82ac1d38e20cda242156364
